spring.application.name=backend
server.port=3000
spring.datasource.url=jdbc:sqlite:recruitly.db?foreign_keys=on&journal_mode=WAL
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.datasource.hikari.maximum-pool-size=1
# app.jwt.secret=your-super-secret
spring.sql.init.mode=never

# LOGGING

logging.file.name=logs/recruitly.log
logging.level.recruitly.backend=DEBUG
logging.level.org.springframework=WARN
